GET http://localhost:1029

# Access-Control-Allow-Credentials: true
# Access-Control-Allow-Headers: Content-Type, Authorization
# Access-Control-Allow-Methods: DELETE, GET, POST
# Content-Length: 17810